backend: tensorflow
class_name: Sequential
config:
- class_name: Conv1D
  config:
    activation: linear
    activity_regularizer: null
    batch_input_shape: !!python/tuple [null, 600, 4]
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
    bias_regularizer: null
    dilation_rate: !!python/tuple [1]
    dtype: float32
    filters: 300
    kernel_constraint: null
    kernel_initializer:
      class_name: VarianceScaling
      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
    kernel_regularizer: null
    kernel_size: !!python/tuple [19]
    name: conv1d_1
    padding: same
    strides: !!python/tuple [1]
    trainable: true
    use_bias: true
- class_name: BatchNormalization
  config:
    axis: 1
    beta_constraint: null
    beta_initializer:
      class_name: Zeros
      config: {}
    beta_regularizer: null
    center: true
    epsilon: 0.001
    gamma_constraint: null
    gamma_initializer:
      class_name: Ones
      config: {}
    gamma_regularizer: null
    momentum: 0.99
    moving_mean_initializer:
      class_name: Zeros
      config: {}
    moving_variance_initializer:
      class_name: Ones
      config: {}
    name: batch_normalization_1
    scale: true
    trainable: true
- class_name: Activation
  config: {activation: relu, name: activation_1, trainable: true}
- class_name: MaxPooling1D
  config:
    name: max_pooling1d_1
    padding: valid
    pool_size: !!python/tuple [3]
    strides: !!python/tuple [3]
    trainable: true
- class_name: Conv1D
  config:
    activation: linear
    activity_regularizer: null
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
    bias_regularizer: null
    dilation_rate: !!python/tuple [1]
    filters: 200
    kernel_constraint: null
    kernel_initializer:
      class_name: VarianceScaling
      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
    kernel_regularizer: null
    kernel_size: !!python/tuple [11]
    name: conv1d_2
    padding: same
    strides: !!python/tuple [1]
    trainable: true
    use_bias: true
- class_name: BatchNormalization
  config:
    axis: 1
    beta_constraint: null
    beta_initializer:
      class_name: Zeros
      config: {}
    beta_regularizer: null
    center: true
    epsilon: 0.001
    gamma_constraint: null
    gamma_initializer:
      class_name: Ones
      config: {}
    gamma_regularizer: null
    momentum: 0.99
    moving_mean_initializer:
      class_name: Zeros
      config: {}
    moving_variance_initializer:
      class_name: Ones
      config: {}
    name: batch_normalization_2
    scale: true
    trainable: true
- class_name: Activation
  config: {activation: relu, name: activation_2, trainable: true}
- class_name: MaxPooling1D
  config:
    name: max_pooling1d_2
    padding: valid
    pool_size: !!python/tuple [4]
    strides: !!python/tuple [4]
    trainable: true
- class_name: Conv1D
  config:
    activation: linear
    activity_regularizer: null
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
    bias_regularizer: null
    dilation_rate: !!python/tuple [1]
    filters: 200
    kernel_constraint: null
    kernel_initializer:
      class_name: VarianceScaling
      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
    kernel_regularizer: null
    kernel_size: !!python/tuple [7]
    name: conv1d_3
    padding: same
    strides: !!python/tuple [1]
    trainable: true
    use_bias: true
- class_name: BatchNormalization
  config:
    axis: 1
    beta_constraint: null
    beta_initializer:
      class_name: Zeros
      config: {}
    beta_regularizer: null
    center: true
    epsilon: 0.001
    gamma_constraint: null
    gamma_initializer:
      class_name: Ones
      config: {}
    gamma_regularizer: null
    momentum: 0.99
    moving_mean_initializer:
      class_name: Zeros
      config: {}
    moving_variance_initializer:
      class_name: Ones
      config: {}
    name: batch_normalization_3
    scale: true
    trainable: true
- class_name: Activation
  config: {activation: relu, name: activation_3, trainable: true}
- class_name: MaxPooling1D
  config:
    name: max_pooling1d_3
    padding: valid
    pool_size: !!python/tuple [4]
    strides: !!python/tuple [4]
    trainable: true
- class_name: Flatten
  config: {name: flatten_1, trainable: true}
- class_name: Dense
  config:
    activation: linear
    activity_regularizer: null
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
    bias_regularizer: null
    kernel_constraint: null
    kernel_initializer:
      class_name: VarianceScaling
      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
    kernel_regularizer: null
    name: dense_1
    trainable: true
    units: 1000
    use_bias: true
- class_name: Activation
  config: {activation: relu, name: activation_4, trainable: true}
- class_name: Dropout
  config: {name: dropout_1, noise_shape: null, rate: 0.3, seed: null, trainable: true}
- class_name: Dense
  config:
    activation: linear
    activity_regularizer: null
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
    bias_regularizer: null
    kernel_constraint: null
    kernel_initializer:
      class_name: VarianceScaling
      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
    kernel_regularizer: null
    name: dense_2
    trainable: true
    units: 1000
    use_bias: true
- class_name: Activation
  config: {activation: relu, name: activation_5, trainable: true}
- class_name: Dropout
  config: {name: dropout_2, noise_shape: null, rate: 0.3, seed: null, trainable: true}
- class_name: Dense
  config:
    activation: linear
    activity_regularizer: null
    batch_input_shape: !!python/tuple
    - null
    - null
    - 12
    - !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [3]
      - !!python/object/apply:numpy.dtype
        args: [i1, 0, 1]
        state: !!python/tuple [3, '|', null, null, null, -1, -1, 0]
      - false
      - !!binary |
        AQAB
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
    bias_regularizer: null
    dtype: float32
    kernel_constraint: null
    kernel_initializer:
      class_name: VarianceScaling
      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
    kernel_regularizer: null
    name: dense_3
    trainable: true
    units: 3
    use_bias: true
- class_name: Activation
  config: {activation: sigmoid, name: activation_6, trainable: true}
keras_version: 2.1.3
